# Form implementation generated from reading ui file 'D:\DETAI_BMHTTT\View\ThietKe\loginDialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 320)
        Dialog.setStyleSheet("background-color:rgb(37, 111, 176);\n"
"color:white;")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 116, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 166, 91, 16))
        self.label_3.setObjectName("label_3")
        self.passwordInput = QtWidgets.QLineEdit(parent=Dialog)
        self.passwordInput.setGeometry(QtCore.QRect(150, 165, 201, 22))
        self.passwordInput.setStyleSheet("background-color: white;\n"
"border: 2px inset #8b6f78;\n"
"color:black;")
        self.passwordInput.setInputMask("")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.usernameInput = QtWidgets.QLineEdit(parent=Dialog)
        self.usernameInput.setGeometry(QtCore.QRect(150, 116, 261, 22))
        self.usernameInput.setStyleSheet("background-color: white;\n"
"border: 2px inset #8b6f78;\n"
"color:black;")
        self.usernameInput.setObjectName("usernameInput")
        self.cancelButton = QtWidgets.QPushButton(parent=Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(280, 236, 93, 28))
        self.cancelButton.setStyleSheet("background-color: rgb(242, 219, 116);\n"
"border-radius: 10px;\n"
"border: 2px solid black;\n"
"color:black;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\DETAI_BMHTTT\\View\\ThietKe\\../Icon/icons8-exit-50.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.cancelButton.setIcon(icon)
        self.cancelButton.setObjectName("cancelButton")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(170, 36, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.loginButton = QtWidgets.QPushButton(parent=Dialog)
        self.loginButton.setGeometry(QtCore.QRect(160, 236, 93, 28))
        self.loginButton.setStyleSheet("background-color: rgb(242, 219, 116);\n"
"border-radius: 10px;\n"
"border: 2px solid black;\n"
"color:black;")
        self.loginButton.setObjectName("loginButton")
        self.showPasswordButton = QtWidgets.QPushButton(parent=Dialog)
        self.showPasswordButton.setGeometry(QtCore.QRect(360, 167, 41, 21))
        self.showPasswordButton.setStyleSheet("background-color: white;\n"
"border: 2px solid black;\n"
"color:black;")
        self.showPasswordButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\DETAI_BMHTTT\\View\\ThietKe\\../Icon/eye.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.showPasswordButton.setIcon(icon1)
        self.showPasswordButton.setObjectName("showPasswordButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "UserName:"))
        self.label_3.setText(_translate("Dialog", "PassWord:"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
        self.label.setText(_translate("Dialog", "Đăng nhập"))
        self.loginButton.setText(_translate("Dialog", "Login"))
